apply plugin: 'com.android.library'

group = 'com.waxbyte.wttspeech'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()

android {
  namespace "com.waxbyte.wttspeech"
  defaultConfig {
    minSdkVersion 24
  }
}

dependencies {
  implementation project(':siteed_sherpa-onnx.rn')
}
